---
- name: check the docker status
  hosts: localhost
  tasks:
          - name: running the script
            command: sudo systemctl "{{action}}" "{{service}}"
            register: output
            failed_when: "'FAILED' in output.stderr"
          - debug: var=output.stdout_lines
          - debug: msg="Requested '{{action}}' for service '{{service}}' on localhost is completed !!"

