---
- name: check the docker status
  hosts: localhost
  become: true
  become_user: root
  become_method: su
  tasks:
          - name: running the script
            command: systemctl "{{action}}" "{{service}}"
            register: output
            failed_when: "'FAILED' in output.stderr"
          - debug: var=output.stdout_lines
          - debug: msg="Requested '{{action}}' for service '{{service}}' on localhost is completed !!"
